fullNameOverride: cms-frontend-deployment

cmsFrontend:
  repository: registry.local:5000/cms-frontend
  pullPolicy: Always
  tag: kidskube-loadtest-92b5b01

migrations:
  enabled: false

ingress:
  enabled: false
