apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cms-backend-mysql
  name: cms-backend-mysql
spec:
  ports:
    - name: default
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: cms-backend-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: cms-backend-mysql
  name: cms-backend-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cms-backend-mysql
  template:
    metadata:
      labels:
        io.kompose.service: cms-backend-mysql
    spec:
      volumes:
        - name: cms-backup
          persistentVolumeClaim:
            claimName: cms-backup
      containers:
        - env:
          - name: MYSQL_DATABASE
            value: cms_db
          - name: MYSQL_ROOT_PASSWORD
            value: root
          image: mysql
          name: mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/docker-entrypoint-initdb.d"
              name: cms-backup
      restartPolicy: Always
