apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
    - name: default
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - name: redis
          command: ["redis-server"]
          args: ["--save", "20", "1", "--loglevel", "debug"]
          image: redis:6.2-alpine
          ports:
            - containerPort: 6379
      restartPolicy: Always
