apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth-backend-deployment
spec:
  hosts:
    - '*'
  gateways:
    - local-gateway
  http:
    - match:
        - uri:
            exact: /transfer
    - route:
        - destination:
            host: auth-service-deployment-svc
            port:
              number: 80
