docker_build('auth-frontend', '../../iam-auth-frontend/deploy')

k8s_yaml(helm('../../kidsloop-helm-charts/helm/charts/auth-frontend', name='auth-frontend-deployment', values='./values.yaml'))

k8s_resource('auth-frontend-deployment', labels=['auth-frontend'], port_forwards=8002, resource_deps=['user-service-postgres'])
