fullNameOverride: auth-frontend-deployment

databases:
  userDb:
    hostname: user-service-postgres

authFrontend:
#  repository: 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-auth-frontend
  repository:  registry.local:5000/auth-frontend
  pullPolicy: Always
#  tag: azure-loadtest-b343a19
  tag: latest

ingress:
  enabled: false

