#k8s_resource(
#  objects=['auth-jwt-credentials:secret', 'live-jwt-credentials:secret', 'kidsloop-cms-backend-db:secret', 'kidsloop-pdf-service-db:secret', 'kidsloop-user-service-api:secret', 'kidsloop-user-service-db:secret', 'kidsloop-xapi-service-db:secret'],
#  new_name='secrets',
#  labels=['secrets'],
#)

k8s_yaml('pact-broker/postgres-deployment.yaml')
k8s_yaml('pact-broker/broker-deployment.yaml')

# add labels to resources create by the above
k8s_resource("pact-broker", labels=["shared-infrastructure"])
k8s_resource("pact-postgres", labels=["shared-infrastructure"])

load('ext://helm_remote', 'helm_remote')
helm_remote(chart='localstack', repo_url='https://helm.localstack.cloud', repo_name='localstack-repo', values='localstack/values.yaml')
k8s_resource('localstack', labels=['shared-infrastructure'], port_forwards=4566)

k8s_resource('pact-postgres', labels=['shared-infrastructure'])
k8s_resource('pact-broker', labels=['shared-infrastructure'], port_forwards='9292:9292', resource_deps=['pact-postgres'])
