apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-backup
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/backup/user"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-backup
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
