apiVersion: v1
kind: Secret
metadata:
  name: kidsloop-user-service-api
data:
  USER_SERVICE_API_KEY: NmQ0ZWRmMGUtYjRjMi0xMWVjLWI5MDktMDI0MmFjMTIwMDAy
type: Opaque
---
apiVersion: v1
data:
  db_name: dXNlcl9zZXJ2aWNlX2Ri
  db_port: NTQzMg==
  hostname: dXNlci1zZXJ2aWNlLXBvc3RncmVz
  password: a2lkc2xvb3A=
  username: a2lkc2xvb3A=
kind: Secret
metadata:
  name: kidsloop-user-service-db
type: Opaque
