docker_build('user-service', '../../user-service/')

k8s_yaml('./pv.yaml')
k8s_yaml('./postgres.yaml')
k8s_yaml('./secrets.yaml')
k8s_yaml(helm('../../kidsloop-helm-charts/helm/charts/user-service', name='user-service-deployment', values='./values.yaml'))

k8s_resource('user-service-postgres', labels=['user-service'])
k8s_resource('user-service-deployment', labels=['user-service'], port_forwards=8005, resource_deps=['user-service-postgres'])
