fullNameOverride: user-service-deployment
domain: fe.sso.kidsloop.live

userService:
  repository: user-service
  pullPolicy: Always
  tag: latest

  database:
    hostname: user-service-postgres
    port: 5432

  assets:
    bucketName: bucket1
    bucketRegion: bucket2

  log:
    level: debug

serviceAccount:
  annotations:
    something: "something something"

ingress:
  enabled: false
